[[bmon]]
arch = "armv7l"
git-tree-sha1 = "002e2fcf9c8a1c836688bbf238265b1e5f3066f4"
libc = "glibc"
os = "linux"

    [[bmon.download]]
    sha256 = "abcb4cb9134dbb6b8b98e07f0417b51230657f8bb83203e72ce307eb29089dd4"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.armv7l-linux-gnueabihf.tar.gz"
[[bmon]]
arch = "i686"
git-tree-sha1 = "657de102430737c0d7ba5b701bcf8ff7ec78cb95"
libc = "musl"
os = "linux"

    [[bmon.download]]
    sha256 = "b925c59b014b546e934ec7db556ee54fe75ffeb6afa22dc423bc7b3082634996"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.i686-linux-musl.tar.gz"
[[bmon]]
arch = "aarch64"
git-tree-sha1 = "613e62f05044063164b7fca644a75145e9dde0f3"
libc = "glibc"
os = "linux"

    [[bmon.download]]
    sha256 = "bd8eac4d62e7e6d364f67ab31323604e58e2ededfd52cd0c2467f9241e671527"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.aarch64-linux-gnu.tar.gz"
[[bmon]]
arch = "armv7l"
git-tree-sha1 = "320414ba8c45f1171958f79734f07c81c899d4c0"
libc = "musl"
os = "linux"

    [[bmon.download]]
    sha256 = "28f7f73b2d6b7e30d3a019d7d40e7e44e895268cbddb780c3195ec15e8a5732b"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.armv7l-linux-musleabihf.tar.gz"
[[bmon]]
arch = "aarch64"
git-tree-sha1 = "278363d36824a2e5312cea5e008e0de88d016059"
libc = "musl"
os = "linux"

    [[bmon.download]]
    sha256 = "cf76235d6b4b7dc5eb00142d42326b76a579f064bad5b511078e9ea26edd9225"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.aarch64-linux-musl.tar.gz"
[[bmon]]
arch = "x86_64"
git-tree-sha1 = "20950155fcf269a3e04ac6bc9e712ec13a485ddd"
os = "macos"

    [[bmon.download]]
    sha256 = "b0e8f0fe0fb14e3e49e1925fc0922ddfbfd9419d870f625f5eb60391810e0d9b"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.x86_64-apple-darwin14.tar.gz"
[[bmon]]
arch = "i686"
git-tree-sha1 = "2bbc35caa58cc9ad52869950f2b53156c42613aa"
libc = "glibc"
os = "linux"

    [[bmon.download]]
    sha256 = "18a2bed42f48d7e75ddb526267a419118500eec8a68ec2f3082018937b086176"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.i686-linux-gnu.tar.gz"
[[bmon]]
arch = "x86_64"
git-tree-sha1 = "6562210cd4258bc00a891962ef6e416b43a3d46a"
libc = "musl"
os = "linux"

    [[bmon.download]]
    sha256 = "e754ab845380fceb962bfd9eaff2d5e0476a87c3cc8e3d6642b8c6c0718a9bda"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.x86_64-linux-musl.tar.gz"
[[bmon]]
arch = "x86_64"
git-tree-sha1 = "22e1e043ffd62ff3e90cd5ced1014fc3d9cb1836"
libc = "glibc"
os = "linux"

    [[bmon.download]]
    sha256 = "060db591c4876968f3a2d9df5cd775e14c1a00694338f296e6bbe0e5d0a4883b"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.x86_64-linux-gnu.tar.gz"
[[bmon]]
arch = "powerpc64le"
git-tree-sha1 = "f84f579869d465b1481bef88393dac1a17f4936d"
libc = "glibc"
os = "linux"

    [[bmon.download]]
    sha256 = "7026340791cffb0a7eba43d3308ad0b12a4daa779436ff45421b0aec1d15d331"
    url = "https://github.com/JuliaBinaryWrappers/bmon_jll.jl/releases/download/bmon-v4.0.0+0/bmon.v4.0.0.powerpc64le-linux-gnu.tar.gz"
